In [1]:
import pandas as pd
from simpledbf import Dbf5
import os
import postal

PyTables is not installed. No support for HDF output.

Lets start this exploration by looking at documents from 2001 Lets open one manually.

In [16]:
dbf = Dbf5('original_data/2001/NFIRS 2001 PDR 031415/hazmat.dbf')

In [17]:
dbf

In [18]:
# What's in the structure?
dbf.columns

['STATE',
 'FDID',
 'INC_DATE',
 'INC_NO',
 'EXP_NO',
 'VERSION',
 'REL_FROM',
 'REL_STORY',
 'POP_DENS',
 'AFFEC_MEAS',
 'AFFEC_UNIT',
 'EVAC_MEAS',
 'EVAC_UNIT',
 'PEOP_EVAC',
 'BLDG_EVAC',
 'HAZ_ACT1',
 'HAZ_ACT2',
 'HAZ_ACT3',
 'OCCUR_FIRS',
 'CAUSE_REL',
 'FACT_REL1',
 'FACT_REL2',
 'FACT_REL3',
 'MIT_FACT1',
 'MIT_FACT2',
 'MIT_FACT3',
 'EQ_INV_REL',
 'HAZ_DISPO',
 'HAZ_DEATH',
 'HAZ_INJ']

In [19]:
# Can we Pandas Dataframe this?
df = dbf.to_dataframe()

In [20]:
df

,STATE,FDID,INC_DATE,INC_NO,EXP_NO,VERSION,REL_FROM,REL_STORY,POP_DENS,AFFEC_MEAS,...,FACT_REL1,FACT_REL2,FACT_REL3,MIT_FACT1,MIT_FACT2,MIT_FACT3,EQ_INV_REL,HAZ_DISPO,HAZ_DEATH,HAZ_INJ
0,AK,11100,5212001,0000856,0,5.0,1,1,NaN,1500,...,54,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN
1,AK,13000,4122001,0000301,0,5.0,1,1,2,2,...,51,NaN,NaN,14,NaN,NaN,342,8,NaN,NaN
2,AK,13000,4182001,0000318,0,5.0,1,1,2,2500,...,43,NaN,NaN,24,NaN,NaN,811,1,NaN,NaN
3,AK,13000,4302001,0000352,0,5.0,1,-1,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,UUU,7,NaN,NaN
4,AK,23100,1012001,0000069,0,5.0,1,0,NaN,300,...,76,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN
5,AK,23100,1082001,0000482,0,5.0,1,0,NaN,80,...,50,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN
6,AK,23100,1162001,0000895,0,5.0,1,1,NaN,100,...,80,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN
7,AK,23100,1232001,0001324,0,5.0,1,0,NaN,1,...,30,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN
8,AK,23100,1262001,0001459,0,5.0,1,0,NaN,20,...,64,NaN,NaN,16,NaN,NaN,NaN,8,NaN,NaN
9,AK,23100,1302001,0001663,0,5.0,1,0,NaN,1,...,30,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN
10,AK,23100,2042001,0001916,0,5.0,2,0,NaN,0,...,70,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
11,AK,23100,2042001,0001933,0,5.0,2,0,NaN,1,...,97,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN
12,AK,23100,2112001,0002298,0,5.0,2,0,NaN,1500,...,75,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
13,AK,23100,2122001,0002383,0,5.0,2,0,NaN,1600,...,52,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN
14,AK,23100,2132001,0002412,0,5.0,2,0,NaN,700,...,78,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN
15,AK,23100,2152001,0002542,0,5.0,2,0,NaN,7000,...,70,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
16,AK,23100,2192001,0002769,0,5.0,2,0,NaN,1,...,64,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN
17,AK,23100,2262001,0003140,0,5.0,2,0,NaN,1500,...,UU,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN
18,AK,23100,2272001,0003194,0,5.0,2,0,NaN,2000,...,30,NaN,NaN,NaN,NaN,NaN,NaN,7,NaN,NaN
19,AK,23100,2282001,0003230,0,5.0,2,0,NaN,500,...,64,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN
20,AK,23100,3042001,0003472,0,5.0,2,0,NaN,1200,...,40,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN
21,AK,23100,3052001,0003541,0,5.0,2,0,NaN,1,...,62,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN
22,AK,23100,3072001,0003625,0,5.0,2,0,NaN,1,...,31,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
23,AK,23100,3102001,0003786,0,5.0,NaN,2,1,0,...,40,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN
24,AK,23100,3132001,0003959,0,5.0,2,0,NaN,1,...,60,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN
25,AK,23100,3222001,0004473,0,5.0,2,0,NaN,2000,...,77,NaN,NaN,NaN,NaN,NaN,141,8,NaN,NaN
26,AK,23100,3312001,0004926,0,5.0,2,0,NaN,20,...,00,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN
27,AK,23100,3312001,0004948,0,5.0,2,0,NaN,100,...,31,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN
28,AK,23100,3312001,0004949,0,5.0,2,0,NaN,1,...,78,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN
29,AK,23100,4052001,0005199,0,5.0,2,0,NaN,20,...,31,NaN,NaN,NaN,NaN,NaN,NaN,7,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4750,WY,05403,7052001,0000833,0,5.0,2,0,NaN,0,...,54,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN
4751,WY,05403,7062001,0000837,0,5.0,2,0,NaN,0,...,71,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN
4752,WY,05403,7092001,0000858,0,5.0,2,0,NaN,0,...,70,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN
4753,WY,05403,7122001,0000878,0,5.0,2,0,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN
4754,WY,05403,7292001,0000984,0,5.0,2,0,3,50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN
4755,WY,05403,10062001,0001370,0,5.0,2,0,3,3,...,71,NaN,NaN,18,NaN,NaN,NaN,2,NaN,NaN
4756,WY,05403,12132001,0001649,0,5.0,1,0,NaN,0,...,71,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN
4757,WY,07437,1192001,0000001,0,5.0,2,0,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
4758,WY,21307,2142001,0002228,0,5.0,1,1,NaN,0,...,70,NaN,NaN,47,NaN,NaN,117,7,NaN,NaN
4759,WY,21307,4272001,0006207,0,5.0,2,0,2,3,...,NaN,NaN,NaN,NN,NaN,NaN,NNN,2,NaN,NaN
4760,WY,21307,5042001,0006584,0,5.0,2,0,NaN,0,...,00,NaN,NaN,NaN,NaN,NaN,NNN,1,NaN,NaN
4761,WY,21307,9302001,0016502,0,5.0,2,0,NaN,0,...,71,NaN,NaN,NaN,NaN,NaN,NNN,1,NaN,NaN
4762,WY,21411,7052001,0000402,0,5.0,2,0,NaN,0,...,54,NaN,NaN,NN,NaN,NaN,NaN,1,NaN,NaN
4763,WY,21427,3162001,0000081,0,5.0,2,0,NaN,0,...,71,NaN,NaN,18,14,NaN,NNN,5,NaN,NaN
4764,WY,21427,6282001,0000198,0,5.0,2,0,NaN,0,...,37,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
4765,WY,25305,1302001,0002701,0,4.1,1,1,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,213,X,0,0
4766,WY,25305,2152001,0002713,0,4.1,1,1,NaN,0,...,50,61,NaN,NaN,NaN,NaN,NaN,2,0,0
4767,WY,25305,3052001,0002721,0,4.1,1,1,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0
4768,WY,25305,3242001,0002729,0,4.1,1,1,NaN,0,...,71,NaN,NaN,NaN,NaN,NaN,NaN,2,0,0
4769,WY,25305,4272001,0002743,0,4.1,1,1,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,0,0
4770,WY,25305,5222001,0002761,0,4.1,1,1,NaN,0,...,54,NaN,NaN,NaN,NaN,NaN,NaN,2,0,0
4771,WY,25305,6302001,0002824,0,4.1,1,1,NaN,0,...,52,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0
4772,WY,25305,7112001,0002853,0,4.1,1,1,NaN,0,...,32,NaN,NaN,NaN,NaN,NaN,NaN,8,0,0
4773,WY,25305,7242001,0002865,0,4.1,1,1,NaN,0,...,76,51,30,NaN,NaN,NaN,300,8,0,0
4774,WY,25515,1172001,0000013,0,5.0,2,0,1,10,...,51,NaN,NaN,NaN,NaN,NaN,344,1,NaN,NaN
4775,WY,29403,6202001,0000111,0,5.0,2,0,NaN,0,...,00,NaN,NaN,NaN,NaN,NaN,NNN,2,NaN,NaN
4776,WY,29509,11102001,0000018,0,5.0,2,0,3,40,...,97,NaN,NaN,NN,NaN,NaN,NNN,5,NaN,NaN
4777,WY,37635,6222001,0000097,0,5.0,1,1,3,0,...,78,NaN,NaN,NaN,NaN,NaN,NNN,1,NaN,NaN
4778,WY,37635,8152001,0000143,0,5.0,2,0,NaN,0,...,50,NaN,NaN,NaN,NaN,NaN,NNN,8,NaN,NaN
4779,WY,41403,1012001,0000001,0,5.0,2,0,3,1,...,54,NaN,NaN,46,10,NaN,NNN,8,NaN,NaN

In [21]:
# Note, when I tried to run this again, it sorta crashed in the same session... Will figure out why later.

In [2]:
dbf_2001 = {}
for file in os.listdir('original_data/2001/NFIRS 2001 PDR 031415/'):
    if file[-3:] == "dbf":
        dbf_2001[file[:-4]] = Dbf5('original_data/2001/NFIRS 2001 PDR 031415/' + file)

In [3]:
dbf_2001.keys()

dict_keys(['ffequipfail', 'arson', 'ems', 'codelookup', 'hazmatequipinvolved', 'wildlands', 'legacyfields', 'hazmat', 'arsonjuvsub', 'civiliancasualty', 'hazmobprop', 'basicincident', 'basicaid', 'ffcasualty', 'arsonagencyreferal', 'hazchem', 'fireincident', 'fdheader'])

In [ ]:
df_2001 = {}
for key in dbf_2001:
    df_2001[key] = dbf_2001[key].to_dataframe()

In [46]:
#It appears reading it from dataframe fries if you try to do it multiple times. So that's not a good thing.

In [ ]:
dbf_2001 = {}
for file in os.listdir('original_data/2001/NFIRS 2001 PDR 031415/'):
    if file[-3:] == "dbf":
        dbf_2001[file[:-4]] = Dbf5('original_data/2001/NFIRS 2001 PDR 031415/' + file)
        
incident01 = dbf_2001["basicincident"].to_dataframe()

In [ ]:
incident01

In [ ]:
incident01.describe()

In [2]:
!in2csv "original_data/2001/NFIRS\ 2001\ PDR\ 031415"

Dockerfile		 LICENSE	README.md	  start-jupyter.sh
first-exploration.ipynb  original_data	requirements.txt  worklog.md